### Quick Recap of Numpy


In [1]:
import numpy as np


In [2]:
first_numpy_array= np.array([1,2,3,4])


In [3]:
print(first_numpy_array)

[1 2 3 4]


In [4]:
#arrays with zeros # use paranthesis for zero array
zero_array = np.zeros((3,3))

In [5]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#array with ones # paranthesis instead of square brackets
one_array = np.ones((3,3))
one_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# array with empty -- create random array
empty_array = np.empty((5,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#array with arange method
arange_array = np.arange(12)
arange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
#reshape the array 
reshape_array = arange_array.reshape(3,4)
reshape_array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
#Linspace for equally spaced data elememts -- np.linspace(first_element,last_element,number_of_equidistanct_element)
lin_space = np.linspace(1,6,5)
print(lin_space)


[1.   2.25 3.5  4.75 6.  ]


In [30]:
#1-D arrays
one_array = np.arange(15)
one_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [107]:
#2-D arrays
two_array = one_array.reshape(3,5)
(two_array)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [106]:
#3-D arrays
three_array = one_array.reshape(3,1,5)
(three_array)

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [39]:
# 0-D arrays
zero_array = np.array(24)
zero_array

array(24)

In [40]:
# shape
three_array.shape 

(3, 1, 5)

In [47]:
# Dimensions -- 0D,1D,2D,3D
two_array.ndim

2

In [53]:
numpy_arr = np.array([x for x in range (1,13)])
print(numpy_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [55]:
## when number of elements not known for a bigdata set we can us this -- 3-D -- use -1 in the last
three_arr = numpy_arr.reshape(2,2,-1)
print(three_arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [59]:
#flatten the matrices
three_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
three_arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [69]:
#ARITHMETIC OPERATIONS
import numpy as np


In [79]:
A = np.array([[1,2,3,4],[9,7,5,2]])
B = np.array([5,6,7,8])


In [80]:
A


array([[1, 2, 3, 4],
       [9, 7, 5, 2]])

In [81]:
B

array([5, 6, 7, 8])

In [82]:
#Addition
np.add(A,B)


array([[ 6,  8, 10, 12],
       [14, 13, 12, 10]])

In [83]:
#subtraction
np.subtract(B,A)

array([[ 4,  4,  4,  4],
       [-4, -1,  2,  6]])

In [84]:
#multiply
np.multiply(A,B)

array([[ 5, 12, 21, 32],
       [45, 42, 35, 16]])

In [86]:
#divide
np.divide(A,B)

array([[0.2       , 0.33333333, 0.42857143, 0.5       ],
       [1.8       , 1.16666667, 0.71428571, 0.25      ]])

In [89]:
#exponetial
print(np.power(A,2))

[[ 1  4  9 16]
 [81 49 25  4]]


In [91]:
print(np.power(A,B))

[[     1     64   2187  65536]
 [ 59049 117649  78125    256]]


In [92]:
## CONDITIONAL STATEMENTS

In [93]:
#Where


In [94]:
import numpy as np

In [97]:
arr_1 = np.array([x for x in range (1,11)])
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
print(np.where(arr_1%2==0,"Even","Odd"))

['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


In [102]:
#Select

In [104]:
cond_list = [arr_1>5,arr_1<5]
choice_list = [arr_1**2,arr_1**3]

np.select(cond_list,choice_list,default=arr_1)

array([  1,   8,  27,  64,   5,  36,  49,  64,  81, 100])

In [108]:
#Statistical functions

In [110]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
np.min(arr)

1

In [112]:
np.max(arr)

9

In [113]:
np.amin(arr,axis=0)

array([1, 2, 3])

In [114]:
np.amin(arr,axis=1)

array([1, 4, 7])

In [115]:
np.amax(arr,axis=0)

array([7, 8, 9])

In [116]:
np.mean(arr)

5.0

In [117]:
np.var(arr)

6.666666666666667

In [118]:
np.median(arr)

5.0

In [119]:
np.std(arr)

2.581988897471611

In [120]:
np.percentile(arr,50)

5.0

In [121]:
deg=np.array([0,30,45,60,90])

In [122]:
deg

array([ 0, 30, 45, 60, 90])

In [136]:
AX = np.sin(deg*np.pi/180)
print(AX)

[0.         0.5        0.70710678 0.8660254  1.        ]


In [133]:
np.tan(deg*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [134]:
np.arcsin(AX)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [137]:
arr = np.array([0.7,-0.4,1.3,2.7])


In [138]:
np.floor(arr)

array([ 0., -1.,  1.,  2.])

In [139]:
np.ceil(arr)

array([ 1., -0.,  2.,  3.])

In [ ]:
# we can do indexing and slicing in arrays using numpy -- 1D,2D,3D

In [140]:
arr[1]

-0.4

In [141]:
arr[1:]

array([-0.4,  1.3,  2.7])